server:
  port: 9091
  servlet:
    context-path: /user-maintenance

spring:
  application:    name: services-config, dao-config
  cloud:    config:      uri: http://localhost:8888

management:  endpoints:    web:      exposure:        include: refresh